Traceback (most recent call last):
  File "/Users/adamimos/anaconda3/envs/epsilon-machine/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adamimos/anaconda3/envs/epsilon-machine/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'learning_rate'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/adamimos/Documents/GitHub/epsilon-transformers/epsilon_transformers/simple_transformer.py", line 309, in sweep_train
    train_hooked_model(model_config, train_loader, test_loader, criterion, num_epochs)
  File "/Users/adamimos/Documents/GitHub/epsilon-transformers/epsilon_transformers/simple_transformer.py", line 219, in train_hooked_model
    learning_rate = wandb.config.learning_rate
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adamimos/anaconda3/envs/epsilon-machine/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'learning_rate'